### ISSUE TITLE
Concurrent Map Writes

### ISSUE THREAD

**Issue by beheh** [xuqingfeng/caddy-rate-limit#13] opened 2017-04-05 00:40 UTC
We're seeing this error in production with Caddy unexpectedly crashing (domain replaced):
```
Apr 05 00:16:33 example.com caddy[20135]: fatal error: concurrent map writes
Apr 05 00:16:33 example.com caddy[20135]: goroutine 43708 [running]:
Apr 05 00:16:33 example.com caddy[20135]: runtime.throw(0xb45fe7, 0x15)
Apr 05 00:16:33 example.com caddy[20135]: /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4208cb208 sp=0xc4208cb1e8
Apr 05 00:16:33 example.com caddy[20135]: runtime.mapassign1(0xa825a0, 0xc42012a0c0, 0xc4208cb3d8, 0xc4208cb398)
Apr 05 00:16:33 example.com caddy[20135]: /usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc4208cb2f0 sp=0xc4208cb208
Apr 05 00:16:33 example.com caddy[20135]: github.com/xuqingfeng/caddy-rate-limit.(*CaddyLimiter).AllowN(0xc420024088, 0xc4202143a0, 0x2, 0x2, 0x5, 0xa, 0xc42025cd40, 0x1, 0x1, 0xc420135020, ...)
Apr 05 00:16:33 example.com caddy[20135]: /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/caddylimiter.go:33 +0x3ad fp=0xc4208cb418 sp=0xc4208cb2f0
Apr 05 00:16:33 example.com caddy[20135]: github.com/xuqingfeng/caddy-rate-limit.(*CaddyLimiter).Allow(0xc420024088, 0xc4202143a0, 0x2, 0x2, 0x5, 0xa, 0xc42025cd40, 0x1, 0x1, 0xc420135020, ...)
Apr 05 00:16:33 example.com caddy[20135]: /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/caddylimiter.go:24 +0x8c fp=0xc4208cb490 sp=0xc4208cb418
Apr 05 00:16:33 example.com caddy[20135]: github.com/xuqingfeng/caddy-rate-limit.RateLimit.ServeHTTP(0xe49480, 0xc420268810, 0xc42022ee00, 0x1, 0x1, 0xe4e100, 0xc4201b8090, 0xc420254000, 0x775310, 0xc4208cb660,
Apr 05 00:16:33 example.com caddy[20135]: /home/caddy/go/src/github.com/xuqingfeng/caddy-rate-limit/ratelimit.go:65 +0x35a fp=0xc4208cb5f8 sp=0xc4208cb490
Apr 05 00:16:33 example.com caddy[20135]: github.com/xuqingfeng/caddy-rate-limit.(*RateLimit).ServeHTTP(0xc420268840, 0xe4e100, 0xc4201b8090, 0xc420254000, 0x0, 0x0, 0xc420227ce0)
Apr 05 00:16:33 example.com caddy[20135]: <autogenerated>:1 +0x8f fp=0xc4208cb660 sp=0xc4208cb5f8
Apr 05 00:16:33 example.com caddy[20135]: github.com/mholt/caddy/caddyhttp/errors.ErrorHandler.ServeHTTP(0xe49780, 0xc420268840, 0x0, 0x0, 0xc420227ce0, 0x0, 0x0, 0xc4202590e0, 0x0, 0x0, ...)
Apr 05 00:16:33 example.com caddy[20135]: /tmp/custombuild_7217_875636448/src/github.com/mholt/caddy/caddyhttp/errors/errors.go:40 +0x129 fp=0xc4208cb7b0 sp=0xc4208cb660
Apr 05 00:16:33 example.com caddy[20135]: github.com/mholt/caddy/caddyhttp/errors.(*ErrorHandler).ServeHTTP(0xc4201eb500, 0xe4e100, 0xc4201b8090, 0xc420254000, 0x1, 0x1, 0x0)
Apr 05 00:16:33 example.com caddy[20135]: <autogenerated>:1 +0xb0 fp=0xc4208cb848 sp=0xc4208cb7b0
Apr 05 00:16:33 example.com caddy[20135]: github.com/mholt/caddy/caddyhttp/gzip.Gzip.ServeHTTP(0xe46700, 0xc4201eb500, 0xc42022ec40, 0x1, 0x1, 0xe4e700, 0xc4200521a0, 0xc420254000, 0x0, 0x0, ...)
Apr 05 00:16:33 example.com caddy[20135]: /tmp/custombuild_7217_875636448/src/github.com/mholt/caddy/caddyhttp/gzip/gzip.go:79 +0x3d3 fp=0xc4208cb988 sp=0xc4208cb848
Apr 05 00:16:33 example.com caddy[20135]: github.com/mholt/caddy/caddyhttp/gzip.(*Gzip).ServeHTTP(0xc420268870, 0xe4e700, 0xc4200521a0, 0xc420254000, 0xc420214360, 0x11, 0x1)
Apr 05 00:16:33 example.com caddy[20135]: <autogenerated>:13 +0x8f fp=0xc4208cb9f0 sp=0xc4208cb988
```

**Comment by xuqingfeng** [comment] 2017-04-05 01:56
Probably duplicate of https://github.com/xuqingfeng/caddy-rate-limit/issues/8

Can you build `caddy` from source with the latest `ratelimit` and give it another try?

**Closed** 2017-04-21 07:24 UTC
Labels: duplicate
